CREATE DATABASE TRASLADOS;
USE TRASLADOS;

CREATE TABLE CAMION(
    IDCAM INT PRIMARY KEY,
    TIPO VARCHAR(50),
    EJES INT,
    CARGA FLOAT,
    FECHA_ADQUISICION DATE,
    NUM_CAM INT
);


CREATE TABLE CLIENTE(
    IDCLIE INT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    APATERNO VARCHAR(100),
    AMATERNO VARCHAR(100),
    FECHANAC DATE,
    COLONIA VARCHAR(100),
    CALLE VARCHAR(100)
);

CREATE TABLE SERVICIOS(
	IDSER INT PRIMARY KEY,
    CONCEPTO VARCHAR(100),
    DIA_NO_LABORAL VARCHAR(100),
    PRECIO FLOAT,
    CARGA_ADIC FLOAT,
    IDCA INT,
    FOREIGN KEY(IDCA) REFERENCES CAMION(IDCAM)
);

CREATE TABLE SOLICITUD(
    CLAVE INT PRIMARY KEY AUTO_INCREMENT,
    FECHA DATE,
    FENTREGA DATE,
    GUIA VARCHAR(100),
    DESCUENTO FLOAT,
    CANTCAM INT,
    SUBTOTAL FLOAT,
    PAGO FLOAT,
    IDCLIENTE INT,
    IDSERVICIO INT,
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIE),
    FOREIGN KEY (IDSERVICIO) REFERENCES SERVICIOS (IDSER)
);


##historial camiones
CREATE TABLE HISTORIAL_CAMION(
    IDH_CAMION INT PRIMARY KEY AUTO_INCREMENT,
    NUEVO_TIPO VARCHAR(100),
    NUEVO_EJES INT,
    NUEVO_CARGA FLOAT,
    NUEVO_USUARIO VARCHAR(100),
    NUEVO_FECHA_HORA DATETIME
);
DROP TABLE HISTORIAL_CAMION;

##historial cliente
CREATE TABLE HISTORIAL_CLIENTE(
    IDH_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    CALLE_ANTERIOR VARCHAR(100),
    CALLE_NUEVA VARCHAR(100),
    COLONIA_ANTERIOR VARCHAR(100),
    COLONIA_NUEVA VARCHAR(100),
    USUARIO VARCHAR(100),
    FECHAHORA DATETIME
);

##Dar de baja servicios
CREATE TABLE DAR_BAJA_SERVICIOS(
    NUEVO_CONCEPTO VARCHAR(100),
    NUEVO_CARGAADICIONAL FLOAT,
    NUEVO_PRECIO FLOAT,
    USUARIO VARCHAR(100),
    FECHA_HORA DATETIME,
    MENSAJE  VARCHAR(100)
);

##bitacora cancelar solicitud
CREATE TABLE BITACORA_SOLICITUD(
    FECHA DATE,
    GUIA VARCHAR(100),
    TOTALPAGAR FLOAT,
    USUARIO VARCHAR(100),
    FECHAHORA DATETIME,
    MENSAJE VARCHAR(100)
);



##para diccionario de datos
SELECT COLUMN_NAME IS_NULLABLE, DATA_TYPE,COLUMN_KEY
	FROM information_schema.COLUMNS WHERE TABLE_SCHEMA ='TRASLADOS'and TABLE_NAME= 'SOLICITUD';

##pruebas de insertar en tablas para los triggers
INSERT INTO CLIENTE(IDCLIE, NOMBRE, APATERNO, AMATERNO, FECHANAC, COLONIA, CALLE)
    VALUES (1, 'HAZEL','JANIS', 'VALDEZ', '1999/02/23','LA BARONA', 'MARIANO MATAMOROS');
INSERT INTO CLIENTE(IDCLIE, NOMBRE, APATERNO, AMATERNO, FECHANAC, COLONIA, CALLE)
    VALUES (20, 'CARLOS','HINIJOSA', 'RIVERA', '1990/02/10','LOMAS', 'TULIPANES');
SELECT *FROM CLIENTE;

INSERT INTO CAMION(IDCAM, TIPO, EJES, CARGA, FECHA_ADQUISICION, NUM_CAM)
    VALUES (1, 'COMERCIAL', 6, 23.5, '2020/09/15', 1);
INSERT INTO CAMION(IDCAM, TIPO, EJES, CARGA, FECHA_ADQUISICION, NUM_CAM)
    VALUES (4, 'CARGA', 8, 5000, '2016/04/23', 6);
SELECT *FROM CAMION;

INSERT INTO SERVICIOS(IDSER, CONCEPTO, DIA_NO_LABORAL, PRECIO, CARGA_ADIC, IDCA)
    VALUES (1,'ASDA','INDEPENDENCIA DE MÉXICO', 203.28, 23.6, 1);
INSERT INTO SERVICIOS(IDSER, CONCEPTO, DIA_NO_LABORAL, PRECIO, CARGA_ADIC, IDCA)
    VALUES (2,'CONSTRUCCION','REVOLUCION MEXICANA', 1000, 5000, 2);
SELECT *FROM SERVICIOS;

INSERT INTO SOLICITUD( FECHA, FENTREGA, GUIA, DESCUENTO, CANTCAM, SUBTOTAL, PAGO, IDCLIENTE, IDSERVICIO)
    VALUES ('2022/05/30','2022/06/07','HAVF',10.0,2,200.80,500.90,1,1);
INSERT INTO SOLICITUD( FECHA, FENTREGA, GUIA, DESCUENTO, CANTCAM, SUBTOTAL, PAGO, IDCLIENTE, IDSERVICIO)
    VALUES ('2022/05/22','2022/05/30','NALSK0731D',10.0,5,5000,4089,3,2);
SELECT *FROM SOLICITUD;


##CREACION DE TRIGGERS
#1 A
DELIMITER //
CREATE TRIGGER insertar_camiones
	BEFORE INSERT ON CAMION
    FOR EACH ROW
    BEGIN
        DECLARE msg VARCHAR(100);
		IF YEAR(NEW.FECHA_ADQUISICION) >= 2016 THEN
			IF NEW.TIPO = 'LONA' THEN
				SET NEW.EJES = 3;
				SET NEW.CARGA = 1000;
				SET NEW.NUM_CAM = 5;
			END IF;
			IF NEW.TIPO = 'CONTENEDOR' THEN
			    SET NEW.EJES = 4;
				SET NEW.CARGA = 2000;
				SET NEW.NUM_CAM = 7;
            END IF;
			IF NEW.TIPO = 'JAULA' THEN
                SET NEW.EJES = 1;
				SET NEW.CARGA = 500;
				SET NEW.NUM_CAM = 8;
            END IF;
			ELSE
		        SET NEW.EJES = 5;
		        SET NEW.CARGA = 1500;
		        SET NEW.NUM_CAM = 4;
		END IF;
		IF YEAR(NEW.FECHA_ADQUISICION) < 2016 THEN
            SET msg = concat('NO CORRESPONDE AL RANGO DE AÑO');
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
        END IF;
    END;

DROP TRIGGER insertar_camiones;
##PRUEBAS PARA EL TRIGGER
INSERT INTO CAMION(IDCAM, TIPO,FECHA_ADQUISICION) VALUES (3, 'CONTENEDOR', '2018/07/10');
INSERT INTO CAMION(IDCAM, TIPO,FECHA_ADQUISICION) VALUES (4, 'JAULA', '2013/09/12');
SELECT * FROM CAMION;


#1B
CREATE TRIGGER Historial_camiones
    AFTER INSERT ON CAMION
    FOR EACH ROW
    BEGIN
        INSERT INTO HISTORIAL_CAMION(NUEVO_TIPO, NUEVO_EJES, NUEVO_CARGA, NUEVO_USUARIO, NUEVO_FECHA_HORA)
        VALUES (NEW.TIPO, NEW.EJES, NEW.CARGA, CURRENT_USER, CURRENT_TIMESTAMP);
    END;
INSERT INTO CAMION(IDCAM, TIPO, EJES, CARGA, FECHA_ADQUISICION, NUM_CAM)
    VALUES (5, 'COMERCIAL', 5, 235.5, '2028/08/12', 3);
DROP TRIGGER  Historial_camiones;
SELECT *FROM CAMION;
SELECT *FROM HISTORIAL_CAMION;


#2A
CREATE TRIGGER NoDarBaja_Cliente
    BEFORE DELETE ON CLIENTE
    FOR EACH ROW
    BEGIN
        DECLARE msg VARCHAR(100);
            IF OLD.COLONIA = 'SAN MIGUEL' OR OLD.COLONIA = 'LOMAS' OR OLD.COLONIA ='SAN PEDRO' THEN
                SET msg = concat('NO SE PUEDE DAR DE BAJA AL CLIENTE');
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = msg;
            END IF;
    END//

DROP TRIGGER NoDarBaja_Cliente;
##PRUEBAS PARA EL TRIGGER
INSERT INTO CLIENTE(IDCLIE, NOMBRE, APATERNO, AMATERNO, FECHANAC, COLONIA, CALLE)
    VALUES (12, 'NOAH','REYES', 'FRANCO', '1999/03/31','LOMAS', 'JACARANDAS');
DELETE FROM CLIENTE WHERE IDCLIE = 12 ;
SELECT *FROM CLIENTE;



#2B
CREATE TRIGGER Historial_clientes
    AFTER UPDATE ON CLIENTE
    FOR EACH ROW
    BEGIN
        IF (OLD.CALLE != NEW.CALLE) OR (OLD.COLONIA != NEW.COLONIA) THEN
            INSERT INTO HISTORIAL_CLIENTE(NOMBRE, CALLE_ANTERIOR, CALLE_NUEVA, COLONIA_ANTERIOR, COLONIA_NUEVA, USUARIO, FECHAHORA)
            VALUES(CONCAT('CLIENTE:', NEW.NOMBRE), CONCAT('CALLE ANTERIOR:', OLD.CALLE), CONCAT('CALLE NUEVA:' , NEW.CALLE),
                   CONCAT('COLONIA ANTERIOR:', OLD.COLONIA), CONCAT('COLONIA NUEVA:' , NEW.COLONIA),
                   CONCAT('USUARIO', CURRENT_USER),  CURRENT_TIMESTAMP);
        END IF;
    END;
##PRUEBAS PARA EL TRIGGER
UPDATE CLIENTE SET NOMBRE = 'LORA' , CALLE = 'BENITO JUAREZ', COLONIA = 'LA JOYA' WHERE IDCLIE = 2;
SELECT *FROM CLIENTE;
SELECT * FROM HISTORIAL_CLIENTE;
DROP TRIGGER Historial_clientes;




#3A
CREATE TRIGGER DarBaja_Servicio
    AFTER DELETE ON SERVICIOS
    FOR EACH ROW
    BEGIN
        INSERT INTO DAR_BAJA_SERVICIOS(NUEVO_CONCEPTO, NUEVO_CARGAADICIONAL, NUEVO_PRECIO, USUARIO, FECHA_HORA, MENSAJE)
        VALUES(OLD.CONCEPTO, OLD.CARGA_ADIC, OLD.PRECIO, CURRENT_USER, CURRENT_TIMESTAMP, 'BAJA DE SERVICIO');
    END;
DROP TRIGGER DarBaja_Servicio;

##PRUEBAS PARA EL TRIGGER
INSERT INTO SERVICIOS(IDSER, CONCEPTO, DIA_NO_LABORAL, PRECIO, CARGA_ADIC, IDCA)
    VALUES (2,'ASDA','INDEPENDENCIA DE MÉXICO', 203.28, 23.6, 1);
DELETE FROM SERVICIOS WHERE IDSER= 2;
SELECT  *FROM SERVICIOS;
SELECT *FROM DAR_BAJA_SERVICIOS;


#4A
CREATE TRIGGER fechas_Entregas
    BEFORE INSERT ON SOLICITUD
    FOR EACH ROW
    BEGIN

        DECLARE NOM, APE, CONCEP, GUIA, CALLE_CLIENTE VARCHAR(100);
        DECLARE FECH DATE;
        DECLARE NUMCAM, IDECAM INT;
        DECLARE PAGO_SERVICIO FLOAT;

        IF dayofweek(NEW.FECHA) = 1 OR 7 THEN
            SET NEW.FENTREGA = ADDDATE(NEW.FECHA, INTERVAL 5 DAY);
        ELSEIF dayofweek(NEW.FECHA) BETWEEN 2 AND 6 THEN
            SET NEW.FENTREGA = ADDDATE(NEW.FECHA, INTERVAL 6 DAY);
            IF DAYOFWEEK(NEW.FENTREGA) = 1 THEN
                SET NEW.FENTREGA = DATE_ADD(NEW.FENTREGA, INTERVAL 1 DAY);
            END IF;
        END IF;

        SELECT C2.NOMBRE, C2.APATERNO, C2.CALLE, FECHA , S.CONCEPTO  into NOM, APE,CALLE_CLIENTE, FECH, CONCEP
            FROM SOLICITUD
            INNER JOIN CLIENTE C2 on SOLICITUD.IDCLIENTE = C2.IDCLIE
            INNER JOIN SERVICIOS S on SOLICITUD.IDSERVICIO = S.IDSER
            WHERE SOLICITUD.IDCLIENTE = NEW.IDCLIENTE;

        SELECT C.NUM_CAM , C.IDCAM, S2.PRECIO  INTO NUMCAM, IDECAM , PAGO_SERVICIO FROM  SOLICITUD
            INNER JOIN SERVICIOS S2 on SOLICITUD.IDSERVICIO = S2.IDSER
            INNER JOIN CAMION C on S2.IDCA = C.IDCAM
            WHERE SOLICITUD.IDSERVICIO = NEW.IDSERVICIO;

        SET GUIA = UPPER( CONCAT(
            LEFT(APE, 2),
            LEFT(NOM, 1),
            LEFT(CONCEP, 2),
            RIGHT(YEAR(FECH), 2))
            );

        SET NUMCAM = NEW.CANTCAM - NUMCAM;
        IF NUMCAM < 0 THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'SOBREPASA EL NUMERO DE CAMIONES';
        END IF;

        UPDATE CAMION SET NUM_CAM = NUMCAM WHERE IDCAM = IDECAM;

        IF (CALLE_CLIENTE = 'LOMAS') THEN
            SET NEW.DESCUENTO = 0.10;
        ELSEIF (CALLE_CLIENTE = 'SAN MIGUEL') THEN
            SET NEW.DESCUENTO = 0.20;
        ELSE
            SET NEW.DESCUENTO = 0.30;
        END IF;

        SET NEW.SUBTOTAL = PAGO_SERVICIO * NEW.CANTCAM;
        SET NEW.PAGO = NEW.SUBTOTAL - (NEW.SUBTOTAL * NEW.DESCUENTO);
        SET NEW.GUIA = GUIA;

    END;

##PRUEBAS PARA EL TRIGGER
INSERT INTO SOLICITUD( FECHA, IDSERVICIO, IDCLIENTE) VALUES ('2020/04/30', 3, 4);
INSERT INTO SOLICITUD( FECHA, FENTREGA, GUIA, DESCUENTO, CANTCAM, SUBTOTAL, PAGO, IDCLIENTE, IDSERVICIO)
    VALUES ('2021/08/23','2021/08/30','LKJS76DSA',20.0 ,8, 1000.89, 800.80,3,3);
SELECT *FROM SOLICITUD;
SELECT *FROM CAMION;
DROP TRIGGER fechas_Entregas;





#4B
CREATE TRIGGER Cancelar_Solicitud
    AFTER DELETE ON SOLICITUD
    FOR EACH ROW
    BEGIN
        INSERT INTO BITACORA_SOLICITUD(FECHA, GUIA, TOTALPAGAR, USUARIO, FECHAHORA, MENSAJE) VALUES
            (OLD.FECHA, OLD.GUIA, OLD.PAGO, CURRENT_USER, CURRENT_TIMESTAMP, 'CANCELACION DE SOLICITUD');
    END;
DROP TRIGGER Cancelar_Solicitud;
##PRUEBAS PARA EL TRIGGER
DELETE FROM SOLICITUD WHERE CLAVE = 2;
SELECT *FROM BITACORA_SOLICITUD;
SELECT *FROM SOLICITUD;



#TRANSACCIONES
#1 INSERTAR DOS REGISTROS DE SERVICIOS Y DAR COMMIT
START TRANSACTION;
INSERT INTO SERVICIOS(IDSER, CONCEPTO, DIA_NO_LABORAL, PRECIO, CARGA_ADIC, IDCA)
    VALUES (6,'CONSTRUCCION','LUNES', 1000, 4000, 3);
INSERT INTO SERVICIOS(IDSER, CONCEPTO, DIA_NO_LABORAL, PRECIO, CARGA_ADIC, IDCA)
    VALUES (8,'MUDANZA','MARTES', 3000, 800, 2);
SELECT *FROM SERVICIOS;
COMMIT;

#2  ACTUALIZAR LOS DATOS DEL CLIENTE CON EL ID NUMERO 2
START TRANSACTION;0
UPDATE CLIENTE SET APATERNO= 'FLORES', AMATERNO = 'MARES',COLONIA = 'CERRITOS',
                   CALLE = 'CUAHNAHUAC' WHERE IDCLIE =  2;
SELECT *FROM CLIENTE WHERE IDCLIE = 2 ;
COMMIT;