CREATE DATABASE ZAPATERIA;
USE ZAPATERIA;

CREATE TABLE EMPLEADO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    FECHA_NAC date,
    SEXO VARCHAR(10),
    SUELDO DOUBLE,
    CATEGORIA VARCHAR(50),
    BONO DOUBLE
);

CREATE TABLE PRODUCTO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(50),
    MARCA VARCHAR(100),
    TALLA DOUBLE,
    PRECIO DOUBLE,
    CANT_EXISTENCIA INT
);
ALTER TABLE  PRODUCTO MODIFY COLUMN TALLA DOUBLE;


CREATE TABLE VENTA(
	SERIE VARCHAR(15),
    FECHA DATE,
    CANTIDAD DOUBLE,
    DESCUENTO INT,
    TOTAL DOUBLE,
    ID_PRO INT,
    ID_EMPLE INT,
    
    FOREIGN KEY(ID_PRO) REFERENCES PRODUCTO(ID),
    FOREIGN KEY(ID_EMPLE) REFERENCES EMPLEADO(ID)
);
#para el diccionario de datos
SELECT COLUMN_NAME IS_NULLABLE, DATA_TYPE,COLUMN_KEY
	FROM information_schema.COLUMNS WHERE TABLE_SCHEMA ='ZAPATERIA'and TABLE_NAME= 'PRODUCTO';



#insertar datos a las tablas
#empleado
INSERT INTO EMPLEADO (NOMBRE, APELLIDO, FECHA_NAC, SEXO, SUELDO, CATEGORIA, BONO) 
	VALUES("FULGENCIA","SANDOVAL", '1993/03/09', "FEMENINO", 1200, "A", 100);
INSERT INTO EMPLEADO(NOMBRE, APELLIDO, FECHA_NAC, SEXO, SUELDO, CATEGORIA, BONO) 
	VALUES("ISRAEL","LUNA", '2000/09/12', "MASCULINO", 1200, "A", 100);
INSERT INTO EMPLEADO(NOMBRE, APELLIDO, FECHA_NAC, SEXO, SUELDO, CATEGORIA, BONO) 
	VALUES("KARLA","LIMA", '1990/02/18', "FEMENINO", 2300, "C", 112);
INSERT INTO EMPLEADO(NOMBRE, APELLIDO, FECHA_NAC, SEXO, SUELDO, CATEGORIA, BONO) 
	VALUES("OLIVER","VEROS", '2001/10/01', "MASCULINO", 2300, "A", 100);
INSERT INTO EMPLEADO(NOMBRE, APELLIDO, FECHA_NAC, SEXO, SUELDO, CATEGORIA, BONO) 
	VALUES("JUAN","GARZA", '1991/06/19', "MASCULINO", 2500, "C", 100);
INSERT INTO EMPLEADO(NOMBRE, APELLIDO, FECHA_NAC, SEXO, SUELDO, CATEGORIA, BONO) 
	VALUES("FERNANDA","ELEAZAR", '1989/12/31', "FEMENINO", 1508, "B", 100);
INSERT INTO EMPLEADO(NOMBRE, APELLIDO, FECHA_NAC, SEXO, SUELDO, CATEGORIA, BONO) 
	VALUES("DELIA","GUADARRAMA", '1990/05/11', "FEMENINO", 3100, "C", 100);
INSERT INTO EMPLEADO(NOMBRE, APELLIDO, FECHA_NAC, SEXO, SUELDO, CATEGORIA, BONO) 
	VALUES("ISELA","RODRIGUEZ", '2000/01/08', "FEMENINO", 2200, "A", 100);
INSERT INTO EMPLEADO(NOMBRE, APELLIDO, FECHA_NAC, SEXO, SUELDO, CATEGORIA, BONO) 
	VALUES("SAMUEL","CASTILLA", '1979/09/30', "MASCULINO", 1900, "B", 100);
INSERT INTO EMPLEADO(NOMBRE, APELLIDO, FECHA_NAC, SEXO, SUELDO, CATEGORIA, BONO) 
	VALUES("CHRISTIAN","LONDRA", '1990/03/12', "MASCULINO", 3000, "C", 100);
SELECT *FROM EMPLEADO ;

#producto
INSERT INTO PRODUCTO(TIPO, MARCA, TALLA, PRECIO, CANT_EXISTENCIA) 
	VALUES("SANDALIA","FLEXI", 25.00, 125.50, 50);
INSERT INTO PRODUCTO(TIPO, MARCA, TALLA, PRECIO, CANT_EXISTENCIA) 
	VALUES("SANDALIA","BOHO SANDALS", 22.5, 180.00, 10);
INSERT INTO PRODUCTO(TIPO, MARCA, TALLA, PRECIO, CANT_EXISTENCIA) 
	VALUES("ZAPATILLA","CHIC ME", 25.5, 300.00, 20);
INSERT INTO PRODUCTO(TIPO, MARCA, TALLA, PRECIO, CANT_EXISTENCIA) 
	VALUES("ZAPATILLA","CLASS", 23.00, 290.99, 23);
INSERT INTO PRODUCTO(TIPO, MARCA, TALLA, PRECIO, CANT_EXISTENCIA) 
	VALUES("ZAPATO HOMBRE","FLEXI", 26.00, 399.99, 20);
INSERT INTO PRODUCTO(TIPO, MARCA, TALLA, PRECIO, CANT_EXISTENCIA) 
	VALUES("ZAPATO MUJER","ART", 24.5, 220.50, 10);
INSERT INTO PRODUCTO(TIPO, MARCA, TALLA, PRECIO, CANT_EXISTENCIA) 
	VALUES("TENIS DEPORTIVO","CHARLY", 25.00, 500.00, 30);
INSERT INTO PRODUCTO(TIPO, MARCA, TALLA, PRECIO, CANT_EXISTENCIA) 
	VALUES("TENIS","FLEXI", 27.00, 308.99, 15);
INSERT INTO PRODUCTO(TIPO, MARCA, TALLA, PRECIO, CANT_EXISTENCIA) 
	VALUES("TENIS","PUMA", 25.5, 319.99, 10);
INSERT INTO PRODUCTO(TIPO, MARCA, TALLA, PRECIO, CANT_EXISTENCIA) 
	VALUES("BOTINES","ROLEX", 22.00, 225.99, 12);
SELECT *FROM PRODUCTO;

#venta
INSERT INTO VENTA(SERIE, FECHA, CANTIDAD, DESCUENTO, TOTAL, ID_PRO, ID_EMPLE) 
	VALUES("V00001", '2022/01/10',2, 5, 285.00, 3, 4);
INSERT INTO VENTA(SERIE, FECHA, CANTIDAD, DESCUENTO, TOTAL, ID_PRO, ID_EMPLE) 
	VALUES("V00002", '2021/01/12',1, 0, 125.00, 1, 9);
INSERT INTO VENTA(SERIE, FECHA, CANTIDAD, DESCUENTO, TOTAL, ID_PRO, ID_EMPLE) 
	VALUES("V00003", '2020/04/13',6, 20, 1440.00, 2, 4);
INSERT INTO VENTA(SERIE, FECHA, CANTIDAD, DESCUENTO, TOTAL, ID_PRO, ID_EMPLE) 
	VALUES("V00004", '2020/12/22',2, 5, 238.45, 1, 3);
INSERT INTO VENTA(SERIE, FECHA, CANTIDAD, DESCUENTO, TOTAL, ID_PRO, ID_EMPLE) 
	VALUES("V00011", '2019/09/19',2, 0, 639.98, 9, 13);
INSERT INTO VENTA(SERIE, FECHA, CANTIDAD, DESCUENTO, TOTAL, ID_PRO, ID_EMPLE) 
	VALUES("V00012", '2019/07/10',1, 0, 290.99, 4, 8);
INSERT INTO VENTA(SERIE, FECHA, CANTIDAD, DESCUENTO, TOTAL, ID_PRO, ID_EMPLE) 
	VALUES("V00013", '2022/01/29',1, 5, 303.99, 9, 10);
INSERT INTO VENTA(SERIE, FECHA, CANTIDAD, DESCUENTO, TOTAL, ID_PRO, ID_EMPLE) 
	VALUES("V00014", '2021/11/10',2, 5, 418.95, 6, 12);
INSERT INTO VENTA(SERIE, FECHA, CANTIDAD, DESCUENTO, TOTAL, ID_PRO, ID_EMPLE) 
	VALUES("V00111", '2019/02/28',3, 10, 486.00, 2, 6);
INSERT INTO VENTA(SERIE, FECHA, CANTIDAD, DESCUENTO, TOTAL, ID_PRO, ID_EMPLE) 
	VALUES("V00112", '2022/02/14',1, 0, 399.99, 5, 7);
SELECT *FROM VENTA;

#1er procedimiento
USE `zapateria`;
DROP procedure IF EXISTS `insertar_Empleado`;

DELIMITER $$
CREATE PROCEDURE `insertar_Empleado` ( 
									  IN nombre VARCHAR(100), 
                                      IN apellido VARCHAR(100),
                                      IN fechaN DATE,
                                      IN genero VARCHAR(100),
                                      IN categoria VARCHAR(100),
                                      IN bono DOUBLE)
proc_label:BEGIN
	
    DECLARE SUELDO int DEFAULT 0;
    DECLARE BONO int DEFAULT 100;
    DECLARE EDAD int DEFAULT 0;
    SET EDAD = year(CURRENT_DATE) - YEAR(fechaN);

	IF categoria = 'A' THEN SET SUELDO = 2500;
    ELSEIF categoria = 'B' THEN SET SUELDO = 3500;
    ELSEIF categoria = 'C' THEN SET SUELDO = 4500;
    ELSE SELECT 'Categoria No encontrada' AS 'ERROR'; LEAVE proc_label;
    END IF;
    
     IF (EDAD >= 18 AND EDAD <= 60) THEN 
		INSERT INTO EMPLEADO(NOMBRE, APELLIDO, FECHA_NAC, SEXO , SUELDO, CATEGORIA, BONO)
  		    VALUES (nombre, apellido, fechaN, genero, SUELDO, categoria, BONO);
		SELECT 'Agregado correctamente' AS 'CORRECTO'; LEAVE proc_label;
    ELSE SELECT 'Edad no permitida en el rango' AS 'ERROR';
    END IF;

END$$
DELIMITER ;

DROP PROCEDURE insertar_empleado;
CALL insertar_Empleado("HUGO", "LOPEZ", current_date(), "FEMENINO", "C", 100);

#comprobar que se insertó
SELECT *FROM EMPLEADO;


#2do procedimiento
CREATE PROCEDURE  InsertProducto(
    IN marcaZapato varchar(100),
    IN TIPO VARCHAR(100),
    IN TALLA DOUBLE,
    IN EXISTENCIA VARCHAR(100))
proc_label:begin
    DECLARE PRECIO INT DEFAULT 0;
    DECLARE CANTIDAD INT DEFAULT 0;

    IF (marcaZapato = 'Flexi') THEN SET PRECIO = 350; SET CANTIDAD = 50;
    ELSEIF (marcaZapato = 'aeropostal') THEN SET PRECIO = 150; SET CANTIDAD = 40;
    ELSEIF (marcaZapato = 'hispana') THEN SET PRECIO = 450; SET CANTIDAD = 30;
    ELSE SELECT 'NO HAY MARCA DE ZAPATO' AS 'ERROR'; LEAVE proc_label;
    END IF;

    INSERT INTO Producto(TIPO, MARCA, TALLA, PRECIO, CANT_EXISTENCIA) VALUE (TIPO, marcaZapato, TALLA, PRECIO, CANTIDAD);

end;
CALL InsertProducto('DDDDD','CONFORT', 24.5, 'ASD');




#3er procedimiento
CREATE PROCEDURE `registro_ventas` (IN serie VARCHAR(15), 
									IN fecha DATE, 
                                    IN cant DOUBLE,
									IN total DOUBLE,
                                    IN idProducto INT,
                                    IN idEmpleado INT)
salir:BEGIN

	DECLARE DESCUENTO DOUBLE DEFAULT 0;
    DECLARE BONO DOUBLE DEFAULT 0;
    DECLARE BONOACTUAL DOUBLE DEFAULT 0;
    DECLARE EXISTENCIA INT DEFAULT 0;
    
    SELECT CANT_EXISTENCIA INTO EXISTENCIA FROM producto WHERE ID_PRO = idProducto;
    
    IF EXISTENCIA = 0 THEN 
		SELECT 'ERROR DE EXISTENCIA';
        LEAVE salir;
    END IF;
    
    
	IF WEEKDAY(fecha) BETWEEN 5 AND 6 THEN 
		SET descuento=0.10;
        SET total = total-(total*descuento);
	END IF;
    
    
    SELECT BONO INTO BONOACTUAL FROM empleado WHERE ID_EMPLE= idEmpleado;
    
    IF cant BETWEEN 1 AND 5 THEN 
		SET BONO = 0.12;
        SET BONOACTUAL = BONOACTUAL+(total*BONO);
    ELSEIF cant BETWEEN 5 AND 10 THEN
		SET BONO =0.17;
        SET BONOACTUAL = BONOACTUAL+(total*BONO);
    ELSEIF cant >=11 THEN
		SET BONO =0.23;
		SET BONOACTUAL = BONOACTUAL+(total*BONO);
    END IF;
    
    UPDATE EMPLEADO SET BONO= BONOACTUAL WHERE ID_EMPLE = idEmpleado;
    
    
    INSERT INTO VENTA(SERIE, FECHA, CANTIDAD, DESCUENTO, TOTAL, ID_PRO, ID_EMPLE) 
		VALUES(serie, fecha, cant, total,idProducto,idEmpleado);
	
END$$
DELIMITER ;

CALL registro_venta("ZCP034", '2022/09/14', 23, 123.24, 3, 5);

#procedimiento 4
CREATE PROCEDURE MOSTRAR_REPORTE(in MarcaProducto varchar(100), in NombreEmpleado varchar(100))
BEGIN
    # 1
    SELECT * FROM Producto WHERE Marca = MarcaProducto;

    #2
    SELECT Nombre, Nacimiento, Sueldo, Bono, Existencia, Fecha, Cantidad, Descuento FROM Venta
        INNER JOIN Empleado E5 on Venta.Idemp = E5.IdEmp
        INNER JOIN Producto P2 on Venta.IdPro = P2.IdPro;

    # 3
    SELECT * FROM Venta JOIN zapateria.Empleado E2 on E2.IdEmp = Venta.Idemp WHERE E2.Nombre = NombreEmpleado;

    # 4
    SELECT * FROM Venta JOIN zapateria.Empleado E3 on E3.IdEmp = Venta.Idemp ORDER BY Nombre;
end;
CALL MOSTRAR_REPORTE('Flexi', 'asd');

#procedimiento 5
CREATE PROCEDURE ActualizarGarantia(in Fecha date, in SERIE_tmp integer, IN TotalVenta DOUBLE)
salir:BEGIN

    IF DATEDIFF( (SELECT Venta.Fecha FROM Venta WHERE Serie = SERIE_tmp),Fecha) < 6 THEN
        UPDATE Venta SET Fecha = Fecha, Total = TotalVenta WHERE Serie = SERIE_tmp;
        SELECT 'ACTUALIZADO CORRECTAMENTE' AS 'CORRECTO';
    ELSE SELECT 'GARANTIA VENCIDA'; LEAVE salir;
    END IF;

end;
INSERT INTO Venta(Fecha, Cantidad, Descuento, Total, IdPro, Idemp) VALUE (CURRENT_DATE, 11, 10, 100, 1, 1);
CALL ActualizarGarantia(CURRENT_DATE, 1, 200);

