CREATE DATABASE GALERIA_DE_ARTE;
USE GALERIA_DE_ARTE;

##CREACION DE TABLAS
CREATE TABLE PINTOR(
    CLAVE INT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    FECNAC DATE,
    LUGAR VARCHAR(100),
    SALARIO FLOAT,
    IMMS FLOAT,
    TIPO VARCHAR(100)
);
DROP TABLE PINTOR;

CREATE TABLE EXPOSICION(
    FOLIO INT PRIMARY KEY,
    TITULO VARCHAR(100),
    FECHA_ESTRENO DATE,
    COSTO FLOAT,
    CUPO INT,
    CLAVE INT,
    FOREIGN KEY(CLAVE) REFERENCES PINTOR (CLAVE)
);

CREATE TABLE BOLETO(
    IDC INT PRIMARY KEY,
    FECHA DATE,
    CANTIDAD INT,
    IVA FLOAT,
    TOTAL FLOAT,
    PROMO VARCHAR(100),
    FOLIO INT,
    FOREIGN KEY(FOLIO) REFERENCES EXPOSICION(FOLIO)
);

##TABLA DE BITACORA PARA NO DAR DE BAJA EXPOSICION TRIGGER 2B
CREATE TABLE BITACORA_EXPOSICION(
    FECHA_ESTRENO DATE,
    V_TITULO VARCHAR(100),
    V_COSTO FLOAT,
    V_PINTOR VARCHAR(100),
    FECHAHORA DATETIME
);

#####TABLA HISTORIAL PINTOR
CREATE TABLE HISTORIAL_PINTOR (
  NOMBRE VARCHAR(100),
  APELLIDO VARCHAR(100),
  SALARIO_ANT FLOAT,
  SALARIO_ACTUAL FLOAT,
  FECHAHORA DATETIME,
  USUARIO VARCHAR(100)
);

CREATE TABLE HISTORIAL_PINTOR2 (
    NOMBRE VARCHAR(100),
    APELLIDO VARCHAR(100),
    FENAC DATE,
    FECHAHORA DATETIME,
    USUARIO VARCHAR(100)
);

##TABLA HISTORIAL BOLETO

CREATE TABLE HISTORIAL_BOLETO(
    FECHA DATE,
    LUAGR VARCHAR(100),
    TOTAL FLOAT,
    FECHAHORA DATETIME,
    USUARIO VARCHAR(100)
);

CREATE TABLE HISTORIAL_BOLETO2(
    LUGAR_ANT VARCHAR(100),
    LUGAR_ACTUAL VARCHAR(100),
    TOTAL_ANT FLOAT,
    TOTAL_ACTUAL FLOAT,
    FECHAHORA DATETIME,
    USUARIO VARCHAR(100)
);


##SECCION DE TRIGGERS
#####TRIGGER 1A
CREATE TRIGGER RANGOS_PINTORES
    BEFORE INSERT ON PINTOR
    FOR EACH ROW
    BEGIN
        DECLARE EDAD_PINTOR INT;
        #OBTENER LA EDAD
        SET EDAD_PINTOR = YEAR(CURRENT_DATE)-YEAR(NEW.FECNAC);

        IF EDAD_PINTOR BETWEEN 18 AND 25 THEN
            SET NEW.SALARIO = 4500;
            SET NEW.IMMS = 0.05;
            SET NEW.TIPO ='SURREALISMO';
        END IF;
        IF EDAD_PINTOR BETWEEN 26 AND 50 THEN
            SET NEW.SALARIO = 8500;
            SET NEW.IMMS = 0.15;
            SET NEW.TIPO ='EXPRESIONISMO';
        END IF;
        IF EDAD_PINTOR > 50 THEN
            SET NEW.SALARIO = 11500;
            SET NEW.IMMS = 0.25;
            SET NEW.TIPO = 'ARTE ABSTRACTO';
        END IF;
       IF EDAD_PINTOR <= 17 THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO APLICA POR SER MENOR DE EDAD';
        END IF;
    END;
##PRUEBAS DEL TRIGGER
#VALIDO
INSERT INTO PINTOR(CLAVE, NOMBRE, APELLIDO, FECNAC, LUGAR)
    VALUES(2, 'KARLA', 'GIRALDO', '2002/03/23', 'BARONA');
#NO VALIDO
INSERT INTO PINTOR(CLAVE, NOMBRE, APELLIDO, FECNAC, LUGAR)
    VALUES(5, 'ALDO', 'DOMAN', '2009/04/13', 'LOMAS DE CORTES');
SELECT *FROM PINTOR;

#####TRIGGER 1B
CREATE TRIGGER DESPEDIR_PINTOR
    BEFORE DELETE ON PINTOR
    FOR EACH ROW
    BEGIN
        DECLARE MSG VARCHAR(100);
        IF OLD.LUGAR = 'CUAUTLA' THEN
            SET MSG = concat('NO SE PUEDE DESPEDIR AL PINTOR');
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MSG;
        END IF;
    END;
##PRUEBAS DEL TRIGGER
INSERT INTO PINTOR(CLAVE, NOMBRE, APELLIDO, FECNAC, LUGAR)
VALUES(6,'FANUEL', 'OLIVARES','1999/02/18', 'CUAUTLA');
DELETE FROM PINTOR WHERE CLAVE = 6;
SELECT *FROM PINTOR;

#####TRIGGER 2A
CREATE TRIGGER FECHAS_PINTOR

    BEFORE INSERT ON EXPOSICION
    FOR EACH ROW
    BEGIN
        DECLARE TIPO VARCHAR(100);

        IF MONTH(NEW.FECHA_ESTRENO) BETWEEN 1 AND 3 THEN
            SET NEW.COSTO = 1000;
            SET NEW.CUPO = 30;
            SELECT PINTOR.TIPO INTO TIPO FROM PINTOR WHERE PINTOR.CLAVE = NEW.CLAVE;
            IF NOT TIPO = 'ARTE ABSTRACTO' THEN
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'DEBE SER EL PINTOR DE TIPO ABSTRACTO';
            END IF;
        END IF;
        IF MONTH(NEW.FECHA_ESTRENO) BETWEEN 4 AND 7 THEN
            SET NEW.COSTO = 1500;
            SET NEW.CUPO =40 ;
            SELECT PINTOR.TIPO INTO TIPO FROM PINTOR WHERE PINTOR.CLAVE = NEW.CLAVE;
            IF NOT TIPO = 'SURREALISMO' THEN
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'DEBE SER EL PINTOR DE TIPO SURREALISMO';
            END IF;
        END IF;
        IF MONTH(NEW.FECHA_ESTRENO) >7 THEN
            SET NEW.COSTO = 1800;
            SET NEW.CUPO =10;
        END IF;
    END;
DROP TRIGGER FECHAS_PINTOR;
##PRUEBAS DEL TRIGGER
INSERT INTO EXPOSICION(FOLIO, TITULO, FECHA_ESTRENO, CLAVE)
VALUES(7, 'ABSTRACTO','2022/02/09', 3);
INSERT INTO EXPOSICION(FOLIO, TITULO, FECHA_ESTRENO, CLAVE)
VALUES(1, 'LA MONA VESTIDA DE SEDA','2021/08/09', 2);
SELECT *FROM EXPOSICION;

##### TRIGGER 2B
##USA TABLA BITACORA_EXPOSICION
CREATE TRIGGER DARBAJA_EXPOSICION
    BEFORE DELETE ON EXPOSICION
    FOR EACH ROW
    BEGIN
        DECLARE NOM VARCHAR(100);
        SELECT PINTOR.NOMBRE INTO NOM FROM PINTOR WHERE PINTOR.CLAVE = OLD.CLAVE;

        INSERT INTO BITACORA_EXPOSICION(FECHA_ESTRENO, V_TITULO, V_COSTO, V_PINTOR, FECHAHORA)
        VALUES(OLD.FECHA_ESTRENO, OLD.TITULO, OLD.COSTO, NOM, CURRENT_TIMESTAMP);
    END;
##PRUEBAS DEL TRIGGER
INSERT INTO EXPOSICION(FOLIO, TITULO, FECHA_ESTRENO, CLAVE) VALUES(4, 'PAJARO SOÑADOR','2022/09/23',3);
DELETE FROM EXPOSICION WHERE FOLIO = 4;
SELECT  *FROM BITACORA_EXPOSICION;


#####TRIGGER 3A
CREATE TRIGGER BOLETOS
    BEFORE INSERT ON BOLETO
    FOR EACH ROW
    BEGIN
        DECLARE FECHA DATE;
        DECLARE DESCUENTO  FLOAT;
        DECLARE MSG VARCHAR(100);
        SELECT FECHA_ESTRENO  INTO FECHA FROM EXPOSICION WHERE  FOLIO = NEW.FOLIO;
        SET DESCUENTO = NEW.TOTAL*0.16;
        SET NEW.TOTAL = NEW.TOTAL-(DESCUENTO);
        IF NEW.FECHA > FECHA THEN
            SET MSG = concat('EL BOLETO NO CORREPSONDE');
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MSG;
        END IF;
    END;
##
INSERT INTO BOLETO(IDC, FECHA, CANTIDAD, IVA, FOLIO)
VALUES(1, '2020/09/08', 2, 23,1);
DROP TRIGGER BOLETOS;

#### TRIGGER 4A
CREATE TRIGGER NODARBAJA_PINTORES
    BEFORE DELETE ON PINTOR
    FOR EACH ROW
    BEGIN
        DECLARE MSG VARCHAR(100);
        IF OLD.LUGAR ='CUAUTLA' OR OLD.LUGAR ='CUERNAVACA' OR OLD.LUGAR ='YAUTEPEC' THEN
            SET MSG = concat('NO SE PUEDE DESPEDIR AL PINTOR');
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MSG;
        END IF;
    END;
##PRUEBAS DEL TRIGGER
INSERT INTO PINTOR(CLAVE, NOMBRE, APELLIDO, FECNAC, LUGAR)
 VALUES(8, 'LORA','CASTILLO','1990/03/23','YAUTEPEC');
SELECT *FROM PINTOR;
DELETE FROM PINTOR WHERE CLAVE = 8;


##TRIGGERS DE HISTORIALES
##PINTOR
##1
CREATE TRIGGER HISTORIAL_PINTOR
    AFTER UPDATE ON PINTOR FOR EACH ROW
    BEGIN
        IF NEW.SALARIO != OLD.SALARIO THEN
            INSERT INTO HISTORIAL_PINTOR (NOMBRE, APELLIDO, SALARIO_ANT, SALARIO_ACTUAL, FECHAHORA, USUARIO)
                VALUES (OLD.NOMBRE, OLD.APELLIDO, OLD.SALARIO, NEW.SALARIO, CURRENT_TIMESTAMP, CURRENT_USER);
        END IF;
    END ;
DROP TRIGGER HISTORIAL_PINTOR;
##PRUEBAS DEL TRIGGER
UPDATE PINTOR SET NOMBRE = 'SOFIA', SET SALARIO = 2300 WHERE CLAVE  = 2;
SELECT *FROM HISTORIAL_PINTOR;

##2
CREATE TRIGGER HISTROIAL_PINTOR2
    BEFORE DELETE ON PINTOR
    FOR EACH ROW
    BEGIN
        INSERT INTO HISTORIAL_PINTOR2(NOMBRE, APELLIDO, FENAC, FECHAHORA, USUARIO)
            VALUES (OLD.NOMBRE, OLD.APELLIDO, CURRENT_TIMESTAMP, CURRENT_USER);
    END;
##PRUEBAS
DELETE FROM PINTOR WHERE CLAVE = 2;
SELECT *FROM HISTORIAL_PINTOR2;


#BOLETO
#1
CREATE TRIGGER HISTORIAL_BOLETO
    BEFORE INSERT ON BOLETO
    FOR EACH ROW
    BEGIN
        DECLARE LUGAR VARCHAR(100);
        SELECT P.LUGAR INTO LUGAR FROM BOLETO
            INNER JOIN EXPOSICION E on BOLETO.FOLIO = E.FOLIO
            INNER JOIN PINTOR P on E.CLAVE = P.CLAVE
            WHERE BOLETO.FOLIO = NEW.FOLIO;

        INSERT INTO HISTORIAL_BOLETO(FECHA, LUAGR, TOTAL, FECHAHORA, USUARIO)
            VALUES(NEW.FECHA, LUGAR, NEW.TOTAL, CURRENT_TIMESTAMP, CURRENT_USER );
    END;

#2
CREATE TRIGGER BOLETO2
    AFTER UPDATE ON BOLETO
    FOR EACH ROW
    BEGIN
         DECLARE LUGAR VARCHAR(100);
         DECLARE LUGAR2 VARCHAR(100);

        SELECT P.LUGAR INTO LUGAR FROM BOLETO
            INNER JOIN EXPOSICION E on BOLETO.FOLIO = E.FOLIO
            INNER JOIN PINTOR P on E.CLAVE = P.CLAVE
            WHERE BOLETO.FOLIO = OLD.FOLIO;

        SELECT P.LUGAR INTO LUGAR2 FROM BOLETO
            INNER JOIN EXPOSICION E on BOLETO.FOLIO = E.FOLIO
            INNER JOIN PINTOR P on E.CLAVE = P.CLAVE
            WHERE BOLETO.FOLIO = NEW.FOLIO;

        INSERT INTO HISTORIAL_BOLETO2(LUGAR_ANT, LUGAR_ACTUAL, TOTAL_ANT, TOTAL_ACTUAL, FECHAHORA, USUARIO)
        VALUES(LUGAR, LUGAR2, OLD.TOTAL, NEW.TOTAL, CURRENT_TIMESTAMP, CURRENT_USER);
    END;
##PRUEBA DEL TRIGGER

